# Spring properties
spring:
  application:
    name: PortalLogApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta
  flyway:
    enabled: false

# HTTP Server
server:
  port: ${PORT:2230}   # HTTP (Tomcat) port

tailsocket:
  port: 5555

management:     # If you set off security...
  security:
    enabled: false

# CloudFoundry API Url
cloudfoundry:
  cc:
    api:
      url: https://api.<DOMAIN>
      uaaUrl: https://uaa.<DOMAIN>
      sslSkipValidation: true
  # CloudFoundry Login information
  user:
    admin:
      username: <CF_USER_ADMIN_USERNAME>            # (e.g. admin)
      password: <CF_USER_ADMIN_PASSWORD>            # (e.g. admin)
    uaaClient:
      clientId: <UAA_CLIENT_ID>                     # (e.g. login)
      clientSecret: <UAA_CLIENT_SECRET>             # (e.g. login-secret)
      adminClientId: <UAA_ADMIN_CLIENT_ID>          # (e.g. admin)
      adminClientSecret: <UAA_ADMIN_CLIENT_SECRET>  # (e.g. admin-secret)
      skipSSLValidation: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://<PORTAL_REGISTRATION_IP>:<PORTAL_REGISTRATION_PORT>/eureka/
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10

# InfluxDB Access Info
influxdb:
  ip: 10.0.1.115
  url: http://10.0.1.115:8086
  username: admin
  password: PaaS-TA2022
  database: logging_db
  measurement: logging_measurement
  retention-policy: autogen
  limit: 50
  httpsEnabled: false


#Spring config setting (current version not used)
#  boot:
#    #Spring boot admin settings
#    admin:
#      routes:
#        endpoints: env,metrics,trace,info,trace,heapdump,hystrix.stream,docs
#        #Timeintervalin ms to update the status of App
#      monitor:
#        perio: 10000
#        #LifeTime of App status in ms.
#        status-lifetime: 10000
#        #Connection Timeout in ms when App's status and info
#        connect-timeout: 2000
#        #Read Timeout in ms when App's status and info
#        read-timeout: 5000
#      metadata-keys-to-sanitize: .password$,.*secret$,.*key$,.$token$,.credentials.,.*vcap_services$
